# Generated by Django 6.0.3 on 2026-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Cleaning', 'Cleaning'), ('Repair', 'Repair'), ('Security', 'Security'), ('Utility', 'Utility'), ('Other', 'Other')], default='Maintenance', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_month', models.DateField(help_text='Use first day of month, example: 2026-03-01')),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='phone',
        ),
        migrations.AddField(
            model_name='house',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateField(help_text='Use first day of month, example: 2026-03-01'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=20),
        ),
    ]
