# Generated by Django 6.0.3 on 2026-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_expense_remove_house_phone_house_monthly_fee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateField(),
        ),
    ]
